<?php
//do not edit this file, gets overwritten by admin actions
//created 2018-11-24 01:08:55 +0000
$stringlength=6;
$charstouse='abcdefghkmnpqrtuvwxyz23456789';
$strictlowercase=true;
$bgcolor='000000';
$textcolor='ffffff';
$linecolor='323232';
$sizewidth=200;
$sizeheight=50;
$fontsize=25;
$numberoflines=6;
$thicknessoflines=2;
$allowad=true;



//END OF FILE
